- name: Create Yum Repo file for MySQL
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable MySQL
  ansible.builtin.shell: dnf module disable mysql -y

- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql-community-server
    state: installed

- name: Restarted MySQL
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: MySQL root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1


