
- name: Disable NodeJS
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJS
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Setup App Prerequisites
  ansible.builtin.import_tasks: app-preq.yml

- name: Install NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app


- name: Schecma Setup
  ansible.builtin.import_tasks: mongo-schema.yml
  when: schema is defined

- name: Setup SystemD Service
  ansible.builtin.import_tasks: systemd-setup.yml
