- name: Create Yum Repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongod
  ansible.builtin.shell: dnf install mongodb-org-shell -y

- name: Load Schema
  ansible.builtin.shell: mongo --host mongodb-dev.anysite.info </app/schema/{{component}}.js
